name: Bans
main: to.joe.j2mc.bans.J2MC_Bans
version: 1.0
loadbefore: [IRC]
depend: [Core]
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Ban module.
commands:
  addban:
    description: Adds a ban for a player.
    usage: /addban player reason
    permission: j2mc.bans.ban
    permission-message: Can't let you do that Star Fox
  ban:
    aliases: [b]
    description: Bans the player (accepts partial names)
    usage: /ban player reason
    permission: j2mc.bans.ban
    permission-message: Can't let you do that Star Fox
  kick:
    aliases: [k]
    description: Kicks the player
    usage: /kick player reason
    permission: j2mc.bans.kick
    permission-message: Can't let you do that Star Fox
  unban:
    aliases: [pardon]
    description: Unbans the player
    usage: /unban player
    permission: j2mc.bans.unban
    permission-message: Can't let you do that Star Fox
  j2lookup:
    aliases: [j2]
    description: Look up player's ban history
    usage: /j2lookup player
    permission: j2mc.bans.lookup
    permission-message: Can't let you do that Star Fox
permissions:
  j2mc.bans.ban:
    description: ban
  j2mc.bans.kick:
    description: kick
  j2mc.bans.unban:
    description: unban
  j2mc.bans.lookup:
    description: lookup
  j2mc.bans.admin:
    description: gives access to all the commands
    children:
      j2mc.bans.ban: true
      j2mc.bans.kick: true
      j2mc.bans.unban: true
      j2mc.bans.lookup: true  
